apiVersion: v1
kind: Service
metadata:
  name: custom-etcd-metrics  # Changed name
  namespace: kube-system
  labels:
    app.kubernetes.io/name: custom-etcd-metrics
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 2381
      targetPort: 2381
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: custom-etcd-metrics  # Changed name
  namespace: kube-system
  labels:
    app.kubernetes.io/name: custom-etcd-metrics
subsets:
  - addresses:
      - ip: 192.168.100.21
      - ip: 192.168.100.22
      - ip: 192.168.100.23
    ports:
      - name: metrics
        port: 2381
        protocol: TCP