{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-key-secret",
    "namespace": "cert-manager"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-key-secret",
        "namespace": "cert-manager"
      }
    },
    "encryptedData": {
      "api-key": "AgCCow8QTZxYug+CISmg9QVYi0nQEx99LZx29+A+97rH8ZUaaoGjeNolVXfd1JsxRnMVs1ja04vRuczItirSXimSgRYQehZoq2GsZc1Us08Zi8ZdI8G/1NfpsuocpRLdcq510/Ox3Sj5qu4hA4DSFsyDoSc50ApIhWj3AtmTtba01sjsAGN8V5k5FcSHuXn9wVAlzhCCf0Yie4myjVRlv3q6E4NFjdGc41TZs+fcGZL6N68jOM2FLk0HwGy9MgCuKpTdzqF3c6VhzroQ/937Uo6cpdtPeYXF2ZChyaG5IGjMAEx5jw5Vo0K+KDOM+IfO19kbsMpGqfRCOJZFqiWgnX0jUnhJ/xvUAWzX7UCKofzKQPxGg/X7ebTnlXGrLozwV/agigpRNajE169t28y8PQfPUzSEXKOcRbb6VPdmbMYwx1sRJZfOdgBhOCoshNGYlZFkCymVyKoxya3HeQs8Rksps7JCqp0BU7v1FK53WC4MtQZp5JEORTNKPYzFDWfNrtN/iUyYk6Q+DN1Y+IQ2+kGzJstFlWBZwfPJM189qu+Fmglo16yCUAbmS4QNtMMnztI8vNLvFLh1XQYh5ymqegEFLx/GHrgVFVU2hE4EkbF8+WtCrrKGvCYa/YvvEtTvtnmDoAVYSkMeYfLz9D3qMwk6xGGhC1ITC0ul70rnMzAuyz8Hp0Hzn0WYqnF/Zsyv8ybk0rbxWJM9TOLUX2y0/hHRyEuQ8nPyfxcXmPSltUWWOzGySLb5moXP"
    }
  }
}
