{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-key-secret",
    "namespace": "cert-manager"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-key-secret",
        "namespace": "cert-manager"
      }
    },
    "encryptedData": {
      "api-key": "AgCASQoCvS05p3GRwDUjeL8D2AI2S0FR84dCK8776h8OmWfCLVrzltCs//kG+7iBBydCi7Y/4sSIpZrJtG3pAFyBp6fp4rL1t6iEQDlo/Ow66ihXoXSjcuBsX4QX1Q1xUm7jXVx6KpXf19BprjJR2t2kjY6m0RrwW659+4pIRxegh+iP8XyO0sajtSfoFi0A6JvTRD9L79zFR2mP1k1zqb69cyoGSK29v6gG1kSjYMPsc8KNKCPF0MO6zYsd389JTatCaAI0LGGcVzfbTvEfDv+7JdJ77wHQohkM1YHq4wRrF2t3KDuPfog7XtPq4qOPFIMC6SbIRCOTFrNooK9XeOGwB6//Y+CD/uq4F+E7+hoNugxyvuuoDRXNC/QZyAG+HQOjwRlz4GCEqRTIYu9be7peeynbNgAsO9saD6s35jcGsA8fydDWfZt00Ran6WcpAPbC/68hamOP3wdeH/VYGo37y/pXG/lT8+yoY0EDfp64Y5+2qsAPZr3mTD/Okdjf48Bt2VRVBSuB9YTNILvoiOFEvKjFu/W36Q2O3fgOPqEwv2SoZyLM4Su9BSonerlmdPdV3UM4uOJbbDsa/TmhFDbXp2sEuCxZ4PJyC2BRdSkDaHOcw4QXs7blFB4nHif2a1xC+vXuCZNqdxjo6XUV/ZAvjIqgezMEJkfTmF/3C5YWLFJRDBeqxl8IXCLFUcHFyPrPqzJq/HsWX039j2qRaewW6fqJgQszF3MNKk29TZpp/bSXyysV96ZM"
    }
  }
}
