{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "tsig-key",
    "namespace": "external-dns"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "tsig-key",
        "namespace": "external-dns"
      }
    },
    "encryptedData": {
      "key": "AgBwC2A36XuDPsHlu0giLRz+iscMZJqtkMMEGffWF+yDICmomgNe6WQsdblxOtIUkhTKzHSg76GHOnAuw+p1cyIKq8HoJFeIP7BmwYn5uCHTzVaXkopxP6Da9UDha5NWvhxyYSjLOExHIlzBUMKOPmOvqk8Tn6xsxWQwG8miM1TBjott2rejDECC6oKtAiWs3pSF7gTIcfXndC8SSac3fyhj+ZISSiDQSKXYshvsHXzHFX31z8nzc3rCmJIRWX+kfBoMER2TegoEpe9+P1R0E6KhgbLO8z1CXRC8eXbdbw8hyMtHPnknjzdC3hoFWPGtnPiVNjU1BNmb3g5aypLTPrG+UI0BOjgkRy3nPOPJZzG7cjRKonYUPyKe4gtC2mbZ5kD8Tt9eT8kz5fkvDi3On4RJposNlh1usqSxWwHxXdLsX7toRQj+Ml3JdoMrecM5Qg6T2WtcdsJkA7n7IfBCCxE7CtpqzhkO8tPeXnLvpno1pX1Z3K5on5N2PJ0PpBU6Gxcz0FrEjuxV77hkAvNpFp7mL3eDQ/aqURyAs5/tNxoIy2SIKF9TiuOleVV0AfLWzjAFzoSWRteZl7wvNXoymrAU7fnkz06GNAIxbVF84zOiQn9e4rdRRSGIJyu53xMcAEC7v+GDhDmyMttqCT83gUhbbz8Mg0DCBzix291YEhs6FDBMZtY6Xvvt9kwT2POiL4jvnhTHMFsoDpTzGVgabQRCfPMI8jEd3iZJMYZmaGdBVB9LQB6KdVWkyHk95w=="
    }
  }
}
