{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "telegram-bot-token-secret",
    "namespace": "kube-prometheus-stack"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "telegram-bot-token-secret",
        "namespace": "kube-prometheus-stack"
      }
    },
    "encryptedData": {
      "bot-token": "AgABbxVDGNvmPpm7CsVK46abSj2tLm+qdiyy1InqEBu1X/+aY9Fcjj2rHe2gqiIGuWcgEGBfw/ODeKoLLHQ0A0gWmGDCTKIavch6limlazuVH/tLc5gbcb5HtFaazQBNE/Es5CSTKISCc/hvcg5A5p/OkLFHIJpsA03ple4Eexis80GsnLlM32dlTX9ACLU78qOE8DLBOVs7mlBM7MynX+nQ2qgvb4GBwKGeCZVf70LtKEGM4v7rO4qUijMvOcvgYODLVZZmCW1IIxHmqoM5jg+l70J+ai+bfMitNFexlplSaRUqPY9/BDWYwkgVmtfdN0g0Hr9BfjHQlNMFRdl0AGlIGWuo/b0Zgc7JgwFdNx9UPPl4QL5YzhtJM6OI+mQ7zrU4ke8hQmjEJwLqKx8NWfyoy6hMUtwDGmk25nW3mS+M7zNrqxxC+nBdCGbDbyJsM0ODK2rPFwCgQUkzkdZOllv9gPm83onkMQ1WUEMh4a253a6mC5E5enBt8V89C8ECqu694iDealUDnbUrF5PQH8WI9ZePofijbON9oKliE8UUHJJaY8zUiQPE21XcqyN0Ax9QXglCHx1BBBapLEG+qvNvB8gBCGfyD3+WAKiY612HquWsjplu0vnPCup54ZTGlr3JHgYRhjPQdQySOQwRWo97FBbQvlrS0jSzhe3aZ3zbPfQy9/l8qNMPsNBEtzFSiB5VSPrY0ymdCxoh4A/U4Z4Jpe//w1hQkAw0Nxq6mA8RA6EIEipYqIayoxQpGQPHGG71MOZlNgQg0TLc/K13tNLT"
    }
  }
}
