{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "telegram-bot-token-secret",
    "namespace": "kube-prometheus-stack"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "telegram-bot-token-secret",
        "namespace": "kube-prometheus-stack"
      }
    },
    "encryptedData": {
      "bot-token": "AgBz/DHWObpCnSPpsZYQx7BPaXTuXYqsUUrrPQkVi5RkZhf75XU+oK7wU6n9GPiaPhQG/R5PWESvh0Q8tCp5S016THvuQqKHEqbT4G5hPCv/5/nDT5mofSIrgl5jwYr9iv8wxDM+U2qecA33RLE1sDe5JYvOashF0MCE1dH+11MGGfBQMHaPbnHQiR35UZlirKkpa/3fJQZ/HL6kIp3+JDBxPqWB/IDbB7l7pf83VFf2Pj36DhEil14BYzA5kAHvC/R9b9YsWtemk+sZbJKGdDXAu8f037gRlKOyEa5z2X6zy3R7akxsqfQocUS/NSUxsgc2EtKFDKHio/4UrCcjWvYjkUXtnejpM3lP8OEkrgQGPAn/Uk8QaGK7UceaaZ9/aUTp6eC1UNeLeICWjUBtWdZ5EreroTlbmbxYO1oLkOWEn+OHZjfvxEo5uyp4vqS+jGGryFjvMWntmD2x+Q4MT3/EQkM7JkHqWXFQeEiA0t3MMuJWmp742azU1ra0mTX0FDY7HivCndxOuM4mw0QVyF5XtTAHYnjkoNU84iFpbXMkekzNC1uXyPKB3XKc0NKsSkcifNWQFEb8jtS9WF8ZMCc4wi4S3ZtrM3sTuMGOXiaelH222Xhb7dAD/+lu3cG/hp1dk05bvhPVnf02Z9AQLdGjvJIUEnc2aMKp4HaGbPCE8AZro15f20nDepCEknzJobNW+iiDc0XfqLA++UUbYZH2vexritn0ajSof/NZLhcpm//YHIbL4oBf7KGEVOUf"
    }
  }
}
