{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "netbox-superuser-credentials",
    "namespace": "netbox"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "netbox-superuser-credentials",
        "namespace": "netbox"
      }
    },
    "encryptedData": {
      "password": "AgCLYpjvgyyw7cQbPx/VkXg/npQYhQrmaaRzKc5Pb55CGbDBEbA6FRFAIa/g4NZpuyOq4hBKDl3t2Yl4M9zZmuCMRRCaxj6Rea8V/Mbg/emqOnTy63qBNiISYnMCadUSTQ+947DyRznReZcapdGf6dqvleWOL13eBkHgBsje8I/VsKSDH3N136V1bTz3gO4oZqoteVRVaR51G4inM/CGIdEjhnBbn9ZCZUxcyqNE7Y7GzZu1fxo9ad46neCzAgyusvdfmgQ/LV7mGoc/JRZM6DujLco+yU8ubZEL/JD4vMAEQrcAS1bT1NKP75+VD99DPvaLBYYAL2clkSM0vm8wtgxirVMvmNdfQ2fPuD+zJqL9TMbd3zpCkTP8WdHIGNfdbQDjyqg5STNm5dCFjYbeUcG5Z1C70Iuaj7ILe3BvcV986sNEQ8bW+jkhsxrnrY/eNLKwt9Kaole0Hlt6QSnYMnc3UHjAYUaK1518ISXQfBK4HPn0jpaiXO107Suh826WzlWzp9pqlAmObypVuo9bQ9i6aXNB9y2rtKXPfhBlolmX9zvDiTRCthlKs3yAm1sJT/vVN24po1jioDsAwTjPECDp5n7CiCpfm/wNloXp55XJO0kt4z8BIaZhLgP/0iTWccY/vA6V+tLKrv6shUhMBw2oMMfQIkuh2QFe4UXTESn8DTTdle8FIBZVECio2z7PD4hOEB25AFEeLfPp0DmWGg==",
      "superuser-password": "AgBNIxMH/BKJqaFo9k8RxQ1u/RNxPVApbSnucuPf9NcT6UHsO3I36rnnoe5LAr/b6l64MlCKZNM7K32wVMoDx7mNAlMuCTGSvoYVduAv1yVchFWRWOvT0bUh0rS0cwAVfb/w+xf1/uNUenEQnsX3i+JwdAY/NsCnvilqqiB2dZnc6DxlAEUa9HKDBmkVsQKdLAmwsZQe4fswo73SAYusut7yzKvM5tb9c2r0ej9n0BtYZk/qMFCtnVU4Md44tX422FbSzXydKOx/mhLIaJ4HkZoiuNRrrWJovSowu5Hk7iJsFWx/hYyBkDT2bTOyC7KVSybd7TtrlmWIMMGt97jDQwXNr905Mrrt+o4Ftd6NPjP2CZv1muvDAYNbjpGbg97RWST0kNfLFsGPImS+76aMDrgeuFokesVh1OVVzvRxeJ4lg8PRltyHHx01iidKp5zDvRtS1x+mytiKvOgmGJiBtwUoBvAmPabX8K9rpe4QadN4QqTj1KKAfCYsqPBk8lYMbrBFx/UDAjLoAApJTNvJPuYjOysJi21kuiPvwUhbC8NBgM0D1UBvtK0JoMg3Wu8m8SoBP35I3j1KOEhu4wZtGNR+7+Hrfw7Fr1NSaYk1ay4Dditp6DQH23myBhAkk5eD8JJfkffggwoCT6PEZhHSB4FKG7arE0BOvjq70nV0aZ+8/g6rLDfzDcCd6LQmRkjnjUInpMZxY0FIHsIqjLNAEw=="
    }
  }
}
