{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "pgadmin-container-env",
    "namespace": "pgadmin"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "pgadmin-container-env",
        "namespace": "pgadmin"
      }
    },
    "encryptedData": {
      "PGADMIN_DEFAULT_EMAIL": "AgBKewvh95gvwOs2NQJkFGbkm5m+MT3p9N2/FRYKHaeEIX5+cD8Sca0B9M0Ehs/EWeygWTBkZPdfh99OTGE9xztv8z7fyjqgiR0TbrHZeXAgWV5n4efpolozDI9gNpZ3dUsRcHOs19UC97I0nTn21R5vjL5Gi7fwKZ09b/Y5dlb2vqW7oMkSXDDrXPI/lIdWKiqUeeXdB2b/+WPHkgdPMZq2hmUQMJM4W2ai8lOS895qTjXAetlDyeCAhqNIXXH3gelghjx7xNg/yJyfX+PFd51EgPsSPe91BRPNhUDmrTQQ9crVinRb/wWfRmQx9y1MwSoyccg30VDZE1q1mcp4RPwWrKtXn5L4sR8V8jkMjEgxy2ITV1BbaF6vs3kiQuyLWgzuRCOpQAZtiuPcpSE6TNBTcUK6omkBRGRmqIuASiix8SVqO7JAL4X7eAN+idLKSLFPr02RS7a6NfvTbjM6beCR+29H7ZX0JEVeZR34qFFvMXZR83hV+GN54efIk7m+Xlfit4SLXOTsmhqoQfP2+enT4Aa40uvoIFO9fZnVPjjxmuRHu2n+DUYmY3eghyl44agFFoGvy6Lzv7H3/wu59o5ad3S2EPQKRwE0lK2D6/eAcY+BQmd9Zzng5UUOrzOFKhuyQT5ONcRJH2mr/1ZaZo3GvmQ3iESzUMTahVCsGfG1YAw5e0W/XhQXBwMIVMxEckZ9YM+1ULSDXVSYnfbE4H3okMWkxu4hGlMZSJi6X8bdQGbi",
      "PGADMIN_DEFAULT_PASSWORD": "AgBEbDW5KJFJojWMzWnuFA6VrF2omqBmNfC/7VtC1gSPmi1xG1/TBgr5UBCuh1H+OoahlEUVKhcgzXGC9ysUu3CcorUUlGKLHElELL+qNdvoP7hZuWeyAWnujXa0bptvztpPdHl+rhh1Fev5/ADF+QEHrNw5VV/uZ8R+2/LetJo7qQMCrsT5hqnDkEMzQTygwq7Ygp6cXiaaklA6Ry6zmLGgPC25WFO1u4yY9HRMy6tJz4tuPF2A0dlBjIuXqoVdZ5lXJsdkrKeO87KTU/zwdYMxUnG082bOgnTIhf5+E9kbw8okeuanYGDN6bEQn0pUu7MeILtsVpaxazGR3ByOsFUGQoqTO5YbAVFQnTO1/jEI7wPM2WzHy9eP78FCKLMLuSZ1m+bSXZPsaCbs6g/4f8C3TiRi5qJM4so3eiXJPHA6afN5qmHlU40xfZBIZF901aftCJGestQEyGnoc2E8AG+kR2C9UHbXK58NroIkNc15WMHVZZwdkVEV3uGwazCYaL04FK5yjm8VAICTNsGCPkPRaldoUaUIRFi81sKzuRpOKdKRaFNrbsCJrgFfaYt/H0Ht9UzPrcHCKFDF54cuHRVWRwSVLUofAytG86oYQ65SIa1NLJ48QVtZ4O2S/0rkB+tZU8DUO0krnZITcEs5yZ2WJiSdmfupBS6BNJOudyEn+AeM/tOBLebZUYG7iuRfd080kKeZD8Pz3GVNZvgLx0g="
    }
  }
}
