{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "s3-credentials",
    "namespace": "longhorn-system"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "s3-credentials",
        "namespace": "longhorn-system"
      }
    },
    "encryptedData": {
      "AWS_ACCESS_KEY_ID": "AgAtxXmRpKj0fMNp/kGdyhwNExugarKxzlDR5z5gYbba1BDrioMQZ2+HYK3lK04zwapmQxpChgOSdF/RN3N8yyyfDdCvWu2Wk17lthHu/HZkVc6RKw5usRlA3XSJhclbpVB0HlJVITwT87RIWHOTGBxEkVwBRrNWFSzuWhK/5f8gmJacMPlVlLcv8Z9EFOzk1BKLKe7MsU6EWM1IiIB9Px5/cPdoIeu/WkuaZtOqTYikuj7GtEfsPCa+ikDygsjdGQtR3RUljZwuWSAtBKJEyCmSi+NI2wwuOEO5HA4dSEFK/VPR8rXCWebcVl1W4+fGt0z5xRTcVs2Y5NfkvPPliEggcqcQ/WeEzJLeyfz98LRHSzxgKYzQT1EqJQgB0oJXpac3fsZJrjQ9OxhUdTwOAoMWhxaGCsphwN64ikQZxJdlTBxjmrGj4qTGPb2RQF6aZT5hnInuXXtX06bibZAonZ/gaf7hSGmKorrOFnqFg0+O8EVcm7F4o9vkIVgURXNsVkaAajkUW94jDzgDv4gAohp2oGko1DsGKPS/L/803UPfxgk9tbbLX8fUbYBuV/pIlUqzMq957q5Jl/ogZQwWXtFGXkGfLklWRMt0rta/in5blTrwk8dv6FVd59VTDD0JfoJDBZwhZjyLpzYZ2k4IjayMfCoVLmdtbxlxJM2veJndFiqsclcJRroJ5BzGx65CDhp8ge8qjwORQOftHLuo8YYFtJVHu28k/kp9lw==",
      "AWS_SECRET_ACCESS_KEY": "AgCNITJvmUEPUpHFPjxG4B2H8gOm3jPXffyJ5wf44nlwcC+uyM5ZPud7dxQqMhDm9+J/tNUV9OXqefibdnfhCZuDaNrkv4PThXRfsYjt8Km7kancub8OxPLgPyftnJ2wVZ8GUNyJB1CbAs9nXHqwoXzNRJn4M3062TA63vkbe4jUdRZVxZiOQ0VHwY/58pMQwxVW8m9Tz7pawEvaikT4FLkUJCcs2ZyaiCrGezTsZB2iTMIedNuZgXiUVDmUoFlwk1x24kzeFbP9oPjO34ho5pIUq7lDrJ/tkULpdL9D1rfgtDGcKB6F2deoV7LHz5slwtqRQlP1/zvv+mZIfBAxOjZCbTNYn/ub0/UeDGkrrxcjv2RtT7NS+9ekx+Sh9WYvMwWoPwECK2/pCcwXTduCs1Qd7HmdgYAcjpKpJ+gTUgBaGuQn4SdhWPI6EnmhCrkpN8blqzA/p8hTUQyLYAa9jOSDbQPHpigaqaO0PJpta+fytzb2jD62PU43doDtxgFE6af3R07QBgzytCrHP+yds+sc1gkgAR0d/3O7N6CRv3nS+QD7tPqenu1QeE+KYS+8nVeTPsJCx0ih0ByWXs/zV9ne/eaWOuk+j9XRJD6jiQ89f0p9h6YQtPznjgC7QiS8yVIZ4ODVNQXl4wq0XTS9DlgbQMG0xW2djoiCcDf9+lgPudoS/2PThGUIOkfX9/3XaTC6lyk/Y5AEoxbth6Rjy+sA5rCJNWpDjzQjxlWdBXtRMu2D+2dS6VYwqgHkIcwbKW8GbrlIUWJUH/A4tj9I6QOb"
    }
  }
}
