---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vikunja-general-tls
  namespace: vikunja
spec:
  secretName: vikunja-general-tls
  issuerRef:
    name: issuer-letsencrypt-production
    kind: ClusterIssuer
  commonName: "vikunja.greyroom.net"
  dnsNames:
    - "vikunja.greyroom.net"
