{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "garage-s3-velero-bucket-credentials",
    "namespace": "velero"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "garage-s3-velero-bucket-credentials",
        "namespace": "velero"
      }
    },
    "encryptedData": {
      "credentials": "AgAucTQu+aHkwR7dEXui/g4DrKPp2RO4cAhAv9+JMcwKP9nbRBcSqTURZG7gOPBSoEC7ooL1G7VRUY4S3llwOWfuvz9Qy7Z02LbuZnGv0YxeOQLAZdevgGLOfA8lDAJMBnl/cJg47QbciQm+aKLtJX4H+hwB1D8abUAJwm6ujkKgsFSC5gjJGkJM/ObuzXDS5Kwn2ErCF5RU+C7d1hzs6T5ivE+POFxif2NiJinHB6QPEGVCT3UbCFf0dHzEQd9Dg43Gnwp0qJP1mrRxs8cbNWXwcg0OXHmgOdgsoIDp5owmPKUuvr8Fr5uYGf49DEN34ehW7TcCf5qBf8fMIG2BDQkGYgDuKK+t2KHGPhN9Z8IPcb7UGrgRPBWRP7x8TsQIJqK2G9dd07CSTb1CNm2ns+0z5Z+yGEm1IssKRxd+FvQDJ99W7jIVmL6QBCMK5Vw2bWkt/16E68lTjlz6FyZsyJyo0Ul6yOe6oOOI3vEHzL4lODvZG/7ewUWIM/feAuoJakXqBMF5MOBLMDV/Y9fSMIi70maa9WHi8rf8OVGhxA40UgTv6SsHEPeUJRWa4Z3mCNO54hIF80nJdHTUr52lgA6nDfiu1ehgGLZ04uz04L9OcoTV4DusFz7IsMN9MLun9HLBsXXQBWCf1YTdJSoC0mf62WBGhZnyzyXB5LLYXkO01bE0d5oOGr3dlCtNvii/eVcxkgVjh8cwST9GE2NvBOYjw+WCRcb3UWOHWugDRAS53pff4W/cHZ2sRIdDy9g2kMIhVvkt7mSGbRt6Wfin2BZtL7Z/+7tofx0H9oJWhQwvW0L2zGdXFXivjc+HPGJABe1XNEfzuPOZy7DDUdkgTmaaPNX6hMsvp+ITmZI4KH4SUqmXND5hX1rWwiKD0NQ="
    }
  }
}
