{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "netbox-superuser-credentials",
    "namespace": "netbox"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "netbox-superuser-credentials",
        "namespace": "netbox"
      }
    },
    "encryptedData": {
      "superuser-password": "AgAHT64Wy/1JftaqFKwZZhovH8CIHaEcCFixma6uAfl0rkuyyzuo/DFvPssxpLCtMzFuDl/v5YVibvieEvstooGE0ghZ8iBfkq4SUW9he3p2XgztefQZS1CrtFbWmPuqp4qnXj9T6nF7fubKw6Kdn6SpIOCabu9K3KOZXcDIafgm3dCTXZWPOrnfN3pZ4jMFCvCK8HDVrYBAFobYmNmLUBREpWB2AxumXkHAGUskrsuBkp28gJ248Gg6yp8uzCfhBatHV4L+6TNQnyPAHq9hHJE5bliWdnu4wy0BsLAM2TQfVikJYWmdruTjxeWWKI/rRKMB5zRP9beg5Su1XL7pSawdEPl0oOClF70QLbdEshZ25fESuZD//T3X3ilz+Ig3lmP5ti9hZNKQBcvdKg1cIlPoGhLInqYWFGwh2glEUG0KiRUmbvy/R2fyzUcU2+JNiKG6DiGjpfSJMQ15GfakJpbThjSveiFgPIFJinHgTgFQCzFRl6e3JBT1DD/6otXzJkjO1nmQI5zcjCfrie3++Wt6G2EcAjtABALD8CA0QV5GjqNiNLjxmb2zLJ9FjNOOH1PJbXnMB24vwISF35dFCL6c00fg1TQPEDav+bOKkW/wP1JA89nRaJgk2zwYL80KZnvW4m6ivL+NRaC612VTmr+mHmcKBZvfPRcqoJSA9IlIJ26+aq0t3uvqcV7LSHl5PW4t0VaIEmHtpLYPQNPe7w=="
    }
  }
}
