apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: standalone
  namespace: metallb-system
spec:
  peerAddress: 192.168.100.1
  peerASN: 64513
  myASN: 64514
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: standalone
  namespace: metallb-system
spec:
  addresses:
    - 192.168.100.25/32
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: standalone
  namespace: metallb-system
